#!/usr/bin/env bash
#Script

PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        nohup ./$PROCESS_NAME > /dev/null 2>&1 &
        echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat $PID_FILE)" && rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "No process found to stop."
        fi
        ;;
    restart)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat $PID_FILE)" && rm -f "$PID_FILE"
        fi
        nohup ./$PROCESS_NAME > /dev/null 2>&1 &
        echo $! > $PID_FILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
