#!/usr/bin/env bash
#Script


PROCESS_NAME="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        nohup $PROCESS_NAME > /dev/null 2>&1 &
        echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    
    stop)
        if [[ -f "$PID_FILE" ]]; then
            kill "$(cat $PID_FILE)" && rm -f $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    
    *)
        echo "Usage: 11-manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

